name: built_redux_repatch
version: 0.2.0
description:
   repatch for built_redux
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/built_redux_repatch
dependencies:
  built_redux: "^6.1.1"
  built_value: ^4.1.0

dev_dependencies:
  built_collection: "^1.0.0"
  build_runner: ^0.4.0
  built_value_generator: ^4.1.0
  source_gen: '^0.7.0'
  test: ^0.12.0

environment:
  sdk: ">=1.17.1 <2.0.0"
